# Generated by Django 4.1.2 on 2022-11-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('shorten_name', models.CharField(max_length=50)),
                ('foundation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('enter_year', models.IntegerField()),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_crud.university')),
            ],
        ),
    ]
